events {}

http {
    upstream app_servers {
        server app:8000;
    }

    # 1. Редирект с HTTP (80) на HTTPS (443)
    server {
        listen 80;
        server_name crypt0-parser.duckdns.org;
        return 301 https://$host$request_uri;
    }

    # 2. Настройки безопасного соединения HTTPS (443)
    server {
        listen 443 ssl;
        server_name crypt0-parser.duckdns.org;

        # Пути к сертификатам внутри контейнера Nginx
        ssl_certificate /etc/letsencrypt/live/crypt0-parser.duckdns.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/crypt0-parser.duckdns.org/privkey.pem;

        # Оптимизация SSL (протоколы и шифры)
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
            proxy_pass http://app_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
