"""add_source_column

Revision ID: 9f5df8f75932
Revises: 5c76935a9a66
Create Date: 2026-07-30 12:24:33.721470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f5df8f75932'
down_revision: Union[str, Sequence[str], None] = '5c76935a9a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crypto_prices', sa.Column('source', sa.String(), nullable=True))
    op.create_index(op.f('ix_crypto_prices_id'), 'crypto_prices', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crypto_prices_id'), table_name='crypto_prices')
    op.drop_column('crypto_prices', 'source')
    # ### end Alembic commands ###
