name: Deploy to VPS

on:
  push:
    branches:
      - main  # ⚠️ Если твоя ветка называется master, замени main на master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy code via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/docker-crypto-parser
            git pull
            docker compose up -d --build
